### ISSUE TITLE
Definition for the settings file?

### ISSUE THREAD

**Issue by DavidLozzi** [adobe/reactor-sync#3]
Do you have a definition for the settings file? I've started to reverse engineer it from the code but that seems like too much work ;)

**Comment by ctysse-sxm** [comment]
Also looking for a definition for the settings file.

**Comment by benjaminbytheway** [comment]
@DavidLozzi @ctysse-sxm,  

The settings file can be generated by running through reactor-downloader here:  https://github.com/adobe/reactor-downloader.  

But the settings file is just a json file that looks like this: 

```json
{
  "propertyId": "PR1234567abcdefghijklm",
  // if you need another environment, look here: https://github.com/adobe/reactor-downloader/blob/master/bin/index.js#L111
  "environment": {
    "name": "production",
    "jwt": "https://ims-na1.adobelogin.com/ims/exchange/jwt",
    "aud": "https://ims-na1.adobelogin.com/c/",
    "scope": "https://ims-na1.adobelogin.com/s/",
    "reactorUrl": "https://reactor.adobe.io"
  },
  "integration": {
    "clientId": "copy and paste from client ID or API Key field from overview tab of console.adobe.io integration",
    "clientSecret": "copy and past from client secret button on overview tab of console.adobe.io integration",
    "privateKey": "/path/to/private/key.pem",
    // copy paste from JWT tab of console.adobe.io integration
    "payload": {
      "exp": 1584642055,
      "iss": "YOUR_EC_ORG_ID@AdobeOrg",
      "sub": "YOUR_TECH_ACCOUNT@techacct.adobe.com",
      // the permissions your integration has 
      "https://ims-na1.adobelogin.com/s/etc...": true, 
      "aud": "https://ims-na1.adobelogin.com/c/abcdefg"
    }
  }
}
```

**Comment by ctysse-sxm** [comment]
Thanks @benjaminbytheway! Managed to figure it out this morning. I encountered a separate issue with reactor-downloader, the same one documented in the open [issue](https://github.com/adobe/reactor-downloader/issues/1) on the reactor-downloader repo.

**Comment by benjaminbytheway** [comment]
Ah yes.  Kind of a chicken and egg problem here, but you could also use the settings file for reactor-downloader.

**Comment by DavidLozzi** [comment]
@benjaminbytheway what am I missing? Here's my settings file. I've confirmed I can access the APIs directly via postman using my integration JWT, and the property exists there. I don't know what this script is trying to do and why it wouldn't work.

```
(node:51773) UnhandledPromiseRejectionWarning: Error: ./PR123456789 does not exist.
    at module.exports (/Users/david.lozzi/.npm/_npx/51773/lib/node_modules/@adobe/reactor-sync/bin/utils/fromFile.js:25:11)
    at module.exports (/Users/david.lozzi/.npm/_npx/51773/lib/node_modules/@adobe/reactor-sync/bin/diff/property.js:36:23)
    at module.exports (/Users/david.lozzi/.npm/_npx/51773/lib/node_modules/@adobe/reactor-sync/bin/diff.js:58:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:51773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and my settings.json file
```
{
  "propertyId": "PR123456789", // I use the ID from the URL in Launch, and the ID provided through the APIs
  "environment": {
    "name": "my name", // does this have to match?
    "jwt": "https://ims-na1.adobelogin.com/ims/exchange/jwt", // this and the following don't change right?
    "aud": "https://ims-na1.adobelogin.com/c/",
    "scope": "https://ims-na1.adobelogin.com/s/",
    "reactorUrl": "https://reactor.adobe.io"
  },
  "integration": {
    "clientId": "xxx",
    "clientSecret": "xxx",
    "privateKey": "private.key",
    "payload": { // provided from my JWT tab on the integration
      "exp": 111,
      "iss": "zzz@AdobeOrg",
      "sub": "zzz@techacct.adobe.com",
      "https://ims-na1.adobelogin.com/s/ent_reactor_sdk": true,
      "aud": "https://ims-na1.adobelogin.com/c/zzz"
    }
  }
}
```

If I specify a different client ID I get a whole different error, so I'm confident auth is working here, but it can't find the property. Do I need to configure the property to allow this or something?

**Comment by benjaminbytheway** [comment]
@DavidLozzi, sorry this is an issue that needs to be fixed.  Sync assumes that you already have the property downloaded on your local machine somewhere.  Try to create a directory with the same name as your `propertyId` in the same directory where you are running the command and see what the error is after that...You may need to create a data.json file in the directory too.

**Comment by DavidLozzi** [comment]
ooo so it **is** looking for a literal path on my machine, I'll give that a whirl

**Comment by DavidLozzi** [comment]
I'd be interested in contributing. I can pull code down and work it, how do I test run this locally?

**Comment by benjaminbytheway** [comment]
That would be great!
1) Fork it to your own repo.  
2) Clone down the repo locally to your machine.  
3) Then you can `npm link` the repo's local directory to act like an npm package (https://docs.npmjs.com/cli/link.html).  Once you have done that, get in another folder and run the commands like normal `npx @adobe/reactor-sync ...etc`. 
4) Commit your code to your forked repo
5) Create a pull request back to this one. :)

**Comment by DavidLozzi** [comment]
fantastic! i'll be working this in the next day or two, hope for a PR soon :D we are very interested in getting this working, thanks for the great work so far!

**Comment by Brontojoris** [comment]
It would be great if the reactor-settings.json format could be documented in the readme.
